export const serialCodes = [
    {
        id: 1,
        code: "SUM-8X92",
        batch: "Summer Special",
        status: "used",
        customer: "John Doe",
        date: "2024-06-02",
    },
    {
        id: 2,
        code: "SUM-3A7B",
        batch: "Summer Special",
        status: "used",
        customer: "Jane Smith",
        date: "2024-06-01",
    },
    {
        id: 3,
        code: "WEL-9Y8Z",
        batch: "Welcome Offer",
        status: "unused",
        customer: "-",
        date: "-",
    },
    {
        id: 4,
        code: "WEL-4K2L",
        batch: "Welcome Offer",
        status: "unused",
        customer: "-",
        date: "-",
    },
    {
        id: 5,
        code: "FLA-1M2N",
        batch: "Flash Sale",
        status: "used",
        customer: "Mike Johnson",
        date: "2024-05-25",
    },
    {
        id: 6,
        code: "FLA-3P4Q",
        batch: "Flash Sale",
        status: "used",
        customer: "Sarah Wilson",
        date: "2024-05-25",
    },
];
